package math;

import java.util.Scanner;

/**
 * Created by mrahman on 12/16/16.
 */
public class Factorial {
    static int factRecursion(int number){
        if(number==1){
            return 1;
        }
        int numberFact= factRecursion(number-1)*number;
        return numberFact;
    }

    static int factIteration(int number){
        if(number==1){
            return 1;
        }
        int numberFact=1;
        for (int i=1;i<=number;i++){
            numberFact=numberFact*i;
        }
        return  numberFact;
    }

    public static void main(String[] args) {
        /*
         * Factorial of 5! = 5 x 4 X 3 X 2 X 1 = 120.
         * Write a java program to find Factorial of a given number using Recursion as well as Iteration.
         *
         */


            Scanner sc= new Scanner(System.in);

        System.out.println("Please enter number whose factorial needs to be calculated:");
            int number=sc.nextInt();

            //Fact method using Recursion
           int recursionUsage= Factorial.factRecursion(number);
        System.out.println("This is the result generated by recursion: "+ recursionUsage);

            //Fact method Using Iteration
            int iterationUsage=Factorial.factIteration(number);
        System.out.println("This is the result generated by iteration: "+ iterationUsage);


    }
}
